### PR TITLE
Output release asset contents to standard output

### PR DESCRIPTION
**Pull request by tonerdo**
## Description

An initial stab at supporting sending the contents of a downloaded asset to standard output

## TODOs

Please ensure all of these TODOs are completed before asking for a review.

- [x] Ensure the branch is named correctly with the issue number. e.g: `feature/new-vpc-endpoints-955` or `bug/missing-count-param-434`.
- [x] Update the docs.
- [x] Keep the changes backward compatible where possible.
- [x] Run the pre-commit checks successfully.
- [x] Run the relevant tests successfully.
- [x] Ensure any 3rd party code adheres with our [license policy](https://www.notion.so/gruntwork/Gruntwork-licenses-and-open-source-usage-policy-f7dece1f780341c7b69c1763f22b1378) or delete this line if its not applicable.

## Related Issues

Addresses #101

### CODE REVIEW

**Review by robmorgan — DISMISSED** [review]
@tonerdo LGTM. do you think we need test cases to check the behaviour for a single asset vs multiple assets?

**Comment by tonerdo** [comment]
@robmorgan I agree on test cases and I spent some time thinking through them.. Do you know how to mock a `cli.Context`?

**Comment by robmorgan** [comment]
@tonerdo you could try to create an integration test in `integration_test.go` with something like:

```go
func TestFetchWithStdoutOption(t *testing.T) {
	tmpDownloadPath, err := ioutil.TempDir("", "fetch-stdout-test")
	require.NoError(t, err)

	repoUrl := "https://github.com/gruntwork-io/fetch-test-public"
	releaseTag := "v0.0.4"
	releaseAsset := "hello+world.txt"

	cmd := fmt.Sprintf("fetch --repo %s --tag %s --release-asset %s --stdout false %s", repoUrl, releaseTag, releaseAsset, tmpDownloadPath)
	t.Logf("Testing command: %s", cmd)
	stdoutput, _, err := runFetchCommandWithOutput(t, cmd)
	require.NoError(t, err)

	// Ensure the expected file was downloaded
	assert.FileExists(t, JoinPath(tmpDownloadPath, releaseAsset))

	// When --stdout is specified, ensure the file contents are piped to the standard output stream
	assert.Contains(t, stdoutput, "hello world")
}
```

Maybe if you do a loop with 2 test cases it might cover each code path?

**Comment by tonerdo** [comment]
Ah! Didn't realize we had integration tests. Thanks for the pointer

**Review by robmorgan — APPROVED** [review]
Ok LGTM

**Pull request merged**
