### PR TITLE
Add support for pagination

### LINKED ISSUE #26: Incorrect error: Tag does not exist.
When I run `fetch` as follows:

```
fetch --tag '~>v0.0.1' --repo https://github.com/gruntwork-io/module-security --source-path="/modules/auto-update" /tmp
```

I get the following error:

```
ERROR: Error occurred while computing latest tag that satisfies version contraint expression: -1 - Tag does not exist
```

This is odd because `v0.0.1` exists on this repo and changing the tag constraint expression to `>v0.0.1` makes it work. This is clearly a bug.

### PR DESCRIPTION
**Pull request by brikis98**
This is https://github.com/gruntwork-io/fetch/pull/83 re-opened with some minor clean up. This should fix #26 and #46. Thank you to @m-bal for doing most of the work!

### CODE REVIEW

**Review by ina-stoyanova — APPROVED** [review]
Looks good!

**Comment by m-bal** [comment]
Thank you so much making the changes. Sorry, I been super busy for the past few days, so I wasn't able to work on the changes you suggested. 👍🏽 🙏🏽

**Comment by brikis98** [comment]
Thanks for the review! Merging now.

**Comment by brikis98** [comment]
https://github.com/gruntwork-io/fetch/releases/tag/v0.3.13

**Pull request merged**
